# Generated by Django 3.2.4 on 2021-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_food_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
