# Generated by Django 3.2.4 on 2021-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_max_food_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_food_count',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
