# Generated by Django 3.2.4 on 2021-06-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_max_food_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_food_count',
        ),
    ]
