export const ROOM_LIST_REQUEST = "ROOM_LIST_REQUEST";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";

export const ROOM_TOP_REQUEST = "ROOM_TOP_REQUEST";
export const ROOM_TOP_SUCCESS = "ROOM_TOP_SUCCESS";
export const ROOM_TOP_FAIL = "ROOM_TOP_FAIL";